- .travis.yml
- Gruntfile.js
- lib/firepad.js
- lib/monaco-adapter.js
- package-lock.json
- package.json
- scripts/tag-and-release.js
> Custom package

- .travis.yml
> Use github releases provided by travis

- .travis.yml
> Fix api key

- .travis.yml
- Gruntfile.js
- package.json
> Removed unused deps

- .travis.yml
- Gruntfile.js
- package-lock.json
- package.json
> Transpile the generated file fully

- Gruntfile.js
- package.json
> Use module false for preset env to preserve the value of "this"

- lib/monaco-adapter.js
- package.json
> Handle model change in monaco editor

- lib/monaco-adapter.js
- package-lock.json
- package.json
> Temporarily make monaco editor editable before executing ops

- lib/monaco-adapter.js
- package.json
> Constructor: Remove Check for InstanceOf

- lib/firepad.js
- lib/monaco-adapter.js
- package-lock.json
- package.json
> Dispose fix

- Gruntfile.js
- lib/firebase-adapter.js
- lib/monaco-adapter.js
- package-lock.json
- package.json
> Import only required parts of firebase

- examples/ace.html
- examples/monaco.html
- lib/monaco-adapter.js
- package-lock.json
- package.json
* Set undo method of model directly instead of
overriding executeCommand
> Fix trigger override

- Gruntfile.js
- examples/monaco.html
- lib/firepad.js
- lib/monaco-adapter.js
- package-lock.json
- package.json
> Codepair ng retain

- .gitignore
- CHANGELOG.md
- lib/editor-client.js
- lib/firebase-adapter.js
- lib/firepad.js
- package.json
- yarn.lock
Sync Cursor focused before Firepad connection was established completely by delaying execution. Have `sync` state to inform client if the positions have been synced with remotes. Persist cursor and selection even after disposition.
Trigger error event in failed transaction if reason for failure is other than disconnection.
Signed-off-by: Progyan Bhattacharya <bprogyan@gmail.com>
> [Fix] Cursor: Sync Cursor without Focus Events

- package.json
- src/database-adapter.ts
- src/editor-adapter.ts
- src/editor-client.ts
- src/firebase-adapter.ts
- src/firepad.ts
- src/monaco-adapter.ts
> initiated Flag to fix repetetions

- scripts/tag-and-version
Signed-off-by: Progyan Bhattacharya <bprogyan@gmail.com>
> (fix) scripts/tag-and-release: Change ref to refs in Branch name

- README.md
- scripts/tag-and-version
Changed Stable version tag from `stable` to `latest`.
Signed-off-by: Progyan Bhattacharya <bprogyan@gmail.com>
> (fix) scripts/tag-and-release: Change NPM Tag for Stable Version

- examples/firepad-monaco-example.ts
- src/firepad-monaco.ts
- src/firestore-adapter.ts
WIP: Adding Firestore adapter
NA
> Add firestore adapter

- .github/CONTRIBUTING.md
There was a file name error in the copy command under local setup in `CONTRIBUTING.md` file.
```bash
$ cp configs/firebase.sample.json configs/firebase.json
```
should be 
```bash
$ cp configs/firebase.json.sample configs/firebase.json
```
> doc: fixed copy command in local setup

- src/firestore-adapter.ts
Removed `_userRef` instance and fixed `lastUpdated` check for users query in `src/firestore-adapter.ts`
Firestore doc reference for realtime filtered query: https://firebase.google.com/docs/firestore/query-data/listen#listen_to_multiple_documents_in_a_collection
> removed _userRef and fixed lastUpdated check in firestore adapter

- src/firestore-adapter.ts
> feat: Sync cursor for firestore text operations

- src/firestore-adapter.ts
> fix: Fix ts build

- examples/firepad-monaco-example.ts
- package.json
- src/firebase-adapter.ts
- src/firepad-classic.ts
- src/firepad-monaco.ts
- src/firestore-adapter.ts
- test/factory/database-adapter.factory.ts
- test/firepad-monaco.spec.ts
- yarn.lock
bump down the version to 7x due to downstream implications
NA
> bump down the version to 7x due to downstream implications

- configs/webpack.config.js
- examples/firepad-monaco-example.ts
- package.json
- src/firepad-classic.ts
- src/firepad-monaco.ts
- src/firestore-adapter.ts
- test/factory/database-adapter.factory.ts
- test/firepad-monaco.spec.ts
- yarn.lock
> Add firestore adapter - Clean Branch

- package.json
- src/firebase-adapter.ts
Catch and log firebase errors to console with `console.error`
> feat: log firebase errors to console
